services:
  valgrind:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /cpps/
    #Keep the service running
    command: tail -f /dev/null
